#!/bin/python

import urllib.request, json

city = "Insert Your City"
api_key = "Insert Your API Key"
units = "Insert your units (Default: Kelvin, Options: Metric, Imperial"
unit_key = "Insert your Unit Key(K, C, F)"

weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?q=2759794&APPID=f8384055722110af89da2f02fd2915a8&units=celcius".format(city, api_key, units)).read())[2:-1])

info = weather["weather"][0]["description"].capitalize()
temp = int(float(weather["main"]["temp"]))

print("%s, %i °%s" % (info, temp, unit_key))